FROM openjdk:8

WORKDIR /usr/src/app

RUN apt update && \
    apt install -y git
  
RUN git clone https://github.com/docker-hy/material-applications.git
RUN cd material-applications/spring-example-project && ./mvnw package

EXPOSE 8080
CMD ["/usr/local/openjdk-8/bin/java", "-jar", "/usr/src/app/material-applications/spring-example-project/target/docker-example-1.1.3.jar"]

