FROM ubuntu:20.04

WORKDIR /usr/src/app

COPY app /usr/src/app

RUN apt update

## download tf model
RUN apt install -y curl && \ 
  curl -OL "http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet50_coco_2018_01_28.tar.gz" && \
  mkdir -p ~/.keras/datasets && \
  tar -xzf faster_rcnn_resnet50_coco_2018_01_28.tar.gz && \
  rm faster_rcnn_resnet50_coco_2018_01_28.tar.gz

## download pkg
RUN apt update && \
  DEBIAN_FRONTEND=noninteractive apt install -y protobuf-compiler python3-pip && \
  pip install --upgrade pip && \
  pip install -r requirements.txt

CMD ./main.py
