version: '3'  

services: 
    frontend:
        image: example-frontend
        environment:
            - REACT_APP_BACKEND_URL=http://backend:8080
        ports: 
            - 5000:5000
    backend: 
        image: example-backend
        environment:
            - REQUEST_ORIGIN=http://frontend:5000
            - REDIS_HOST=cache
            - REDIS_PORT=6379
        ports: 
            - 8080:8080
    cache:
        image: redis
