FROM golang:1.16-alpine

WORKDIR /usr/src/app

RUN apk update && \
    apk add git build-base && \
    git clone https://github.com/docker-hy/material-applications.git && \
    mv material-applications/example-backend/* ./ && \
    rm -rf material-applications
RUN go build
RUN go test ./...

ENV REQUEST_ORIGIN http://localhost:5000
		
EXPOSE 8080

CMD ./server
