FROM node:fermium-alpine

WORKDIR /usr/src/app

RUN apk update && \
    apk add git && \
    git clone https://github.com/docker-hy/material-applications.git && \
    mv material-applications/example-frontend/* ./ &&\
    rm -rf material-applications

ENV REACT_APP_BACKEND_URL=http://localhost:8080/
RUN npm install && node -v && npm -v && \
		npm run build && \
		npm install -g serve

EXPOSE 5000

CMD serve -s -l 5000 build
